### ISSUE TITLE
Broken auth

### ISSUE THREAD

**Issue by gliganh** [Perl-Email-Project/Mail-Sender#1]
Hi,

I think this change from b3e4f056535621206e4ed39b3f5fece35f36251f  broke the authentication : 
-    &{"Mail::Sender::Auth::" . $auth}($self);
-    my $method = "Mail::Sender::$auth";
-    $method->($self);

Trying to use PLAIN authentication throws this error : 

Undefined subroutine &Mail::Sender::PLAIN called at /usr/local/share/perl/5.20.2/Mail/Sender.pm line 344

Thanks

**Comment by genio** [comment]
Thanks for the report.  I'll look into testing this ASAP for a fix.

**Comment by genio** [comment]
@gliganh I believe I have corrected this in 960e356 and released version 0.901.  I apologize for the screwup in the previous release.  Please let me know if the problem continues.

I'm slowly adding more and more author tests to ensure these types of things don't happen going forward.

Thanks again!

**Comment by gliganh** [comment]
Many thanks for fixing it so fast !
