### ISSUE TITLE
$Mail::Sender::ver

### ISSUE THREAD

**Issue by Pavel109** [Perl-Email-Project/Mail-Sender#2]
Hello,
the variable $Mail::Sender::ver is used twice in the module Sender.pm, (lines  1237 and 1519) but there is no definition of this variable. I observed it in version 0.901, but I passed 0.902 on this website and it is the same.
It throws error message 
Use of uninitialized value $Mail::Sender::ver in concatenation (.) or string at /usr/local/share/perl5/Mail/Sender.pm line 1517,.....

thank you for fixing
Pavel

**Comment by genio** [comment]
Thank you for the report!  I've addressed it in the repository and will push a release to the CPAN soon for download.

Thanks again!
Chase

**Comment by genio** [comment]
The fix has been shipped in version 0.902.

Thanks,
Chase
- edited to reflect the proper number.
