### ISSUE TITLE
Metadata includes requirement of Try::Tiny that's not used

### ISSUE THREAD

**Issue by pghmcfc** [Perl-Email-Project/Mail-Sender#3]
Makefile.PL, META.json etc. list Try::Tiny as a runtime dependency of Mail::Sender, but it's not used, not even in the test suite. I think it can safely be removed.

**Comment by genio** [comment]
@pghmcfc You're right in that I added the requirement a bit too early.  I think you're also right in that it should not be a runtime requirement.  I'll pull that tonight and make another release that will include some extra tests.

It will need to remain a testing requirement as I am working on a local branch that makes use of Try::Tiny in testing. That branch is getting closer to release-ready and will bring the entire test coverage up considerably (to 34%).

Thanks for the report!  I'll update later tonight.

**Comment by genio** [comment]
Thanks! The prereq for Try::Tiny has been removed. The release will be coming soon.
