### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ggl** [Perl-Email-Project/Mail-Sender#5]
Please get rid of the deprecation warning suggesting Email::Sender instead of Mail::Sender, as the former lacks proper documentation and functionality to attach files. Therefore Mail::Sender is quite useful and still relevant.

**Comment by shadowcat-mst** [comment]
Email::Sender works fine with file attachments; see e.g. Email::Stuffer for a simpler interface if you're having trouble working with Email::MIME.

I agree that Email::Sender's documentation could be expanded, but that doesn't make Mail::Sender either useful or relevant, and allowing users to use Mail::Sender for new code in 2018 without a warning would be a breach of professional ethics.

**Comment by genio** [comment]
Hi! To expand a bit on what @shadowcat-mst said, Mail::Sender development has been halted as it is no longer the best way to accomplish email tasks. It should, indeed, remain deprecated. Looking past that, let's look at the current best practices to accomplish what your goal is:

[Email::Sender](https://metacpan.org/pod/Email::Sender) is the best way to send email currently in Perl. You can see how to create an email object and send it in the [Quick Start Guide](https://metacpan.org/pod/Email::Sender::Manual::QuickStart).

Creating multi-part email messages is done with [Email::MIME](https://metacpan.org/pod/Email::MIME) and friends. To simplify that process for easily attaching files, you will likely find [Email::Stuffer](https://metacpan.org/pod/Email::Stuffer) a much easier starting point.

1) Create the email object with Email::Abstract, Email::MIME, Email::Stuffer, etc.
1) Send the email with Email::Sender/Email::Sender::Simple

I hope that helps. We'll be happy to try to help a bit more interactively in the #perl channel on FreeNode
